version: '3'

services:
  starbot:
    image: sdjnmxd/starbot:latest
    volumes:
      - ./config:/app/config
    environment:
      # B站账号配置（必须）
      - SESSDATA=${SESSDATA}
      - BILI_JCT=${BILI_JCT}
      - BUVID3=${BUVID3}
      
      # Mirai配置（必须）
      - MIRAI_HOST=${MIRAI_HOST:-localhost}
      - MIRAI_PORT=${MIRAI_PORT:-7827}
      
      # Redis配置（必须）
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  redis_data:
    driver: local 